### PR TITLE
🐛 allow commits with reserved regex characters

### LINKED ISSUE #76: [BUG] Crash if commit starts with '*'
Hi,

I tried to use semantic-release-gitmoji today and had this exception:
` An error occurred while running semantic-release: SyntaxError: Invalid regular expression: /^*/: Nothing to repeat`
After searching a bit, I found that this commit was the source of the exception:
`*Merge branch 'main' of ssh://GIT_URL into main`
The problem seems to be due to the emojiRegex. The regex returns "*" which lead to a bad regex for this line:
`subject = subject.replace(new RegExp('^' + gitmoji), '')`

Global workflow:
`const matched = emojiRegex().exec(subject)` subject = *Merge branch 'main' of ssh://GIT_URL into main
`if (!matched || matched.index !== 0) return null`
`const gitmoji = matched[0]` gitmoji = *
`const semver = gitmojis.find(matchEmoji(gitmoji))?.semver || 'other'`
`subject = subject.replace(new RegExp('^' + gitmoji), '')`

### PR DESCRIPTION
**Pull request by djcrabhat**
Closes #76

### CODE REVIEW

**Review by desaintvincent — APPROVED** [review]

**Comment by djcrabhat** [comment]
Sorry to poke @momocow , but I see you releasing this repo again. Mind taking a look at this PR?

**Comment by momocow** [comment]
> Sorry to poke @momocow , but I see you releasing this repo again. Mind taking a look at this PR?

Sure, let me see!

**Comment by momocow** [comment]
I think the main issue in #76 is that `emoji-regex` mis-recognizes the character, `*`, as an emoji.
As a result, the solution should be fixing the emoji recognition instead of escaping regex characters.

Changing the import statement from `require('emoji-regex/text')` to `require('emoji-regex')` should fix the issue.
BTW, there is no `emoji-regex/text` exported in the newer version of package `emoji-regex` anyway.

I'll reject this PR as it's not an ideal solution to #76 and file another one to fix it.

Thanks for poking me. 😉

**Comment by djcrabhat** [comment]
> Thanks for providing an solution at first hand and poking me. 😉


Oh my pleasure and thanks for the deeper, truer fix. I'm a huge fan of your project, it has revolutionized git commit aesthetics and release process for my team ❤️

**Pull request closed without merging**
