### PR TITLE
:bug: fix: Fixed type error

### PR DESCRIPTION
**Pull request by bryanjtc**
Fixes: #57

### CODE REVIEW

**Comment by bryanjtc** [comment]
@momocow Important to merge this!

**Comment by momocow** [comment]
The revision looks good to me.

However, I wonder which emoji you are using when facing this bug and why it is not matched by any emoji from the `gitmojis` package

**Comment by momocow** [comment]
@bryanjtc Please provide the emoji you used when facing this bug and the version of `gitmojis` you were using, to help me determine if this is a bug of emoji matching like #55 (also see carloscuesta/gitmoji#753).

Anyway, thank you for your fact reaction to this! :)

**Comment by bryanjtc** [comment]
# I was using the Hammer emoji and gitmojis 3.13.2

**Comment by bryanjtc** [comment]
The Hammer emoji semver value is null. That's why I added the optional chaining in the pr.

**Comment by momocow** [comment]
`null` value of `semver` actually won't lead to `TypeError: Cannot read properties of undefined (reading 'semver')` because the error is arguing the object where `semver` key resides to be undefined, not the value itself of the key. 🤔

**Comment by momocow** [comment]
The first thing that should be found out is why `:hammer:` did not match anything from `gitmojis` package.

I'll try to reproduce it first.

**Pull request merged**
